### ISSUE TITLE
New Install, Reschedule from zayo is failing

### ISSUE THREAD

**Issue by dnyt84** [wasabi222/janitor#33]
Hello,

when processing the inbox I have a Rescheduled Maintenance from Zayo that it is failing on:

[2020-10-19 15:36:15,405] INFO in Providers: attempting to process email RESCHEDULE NOTIFICATION***XXX Inc***ZAYO TTN-XXX
 Planned***
[2020-10-19 15:36:15,414] INFO in Providers: attempting to mark maintenance rescheduled
[2020-10-19 15:36:15,418] INFO in Providers: attempting to add new maint from email RESCHEDULE NOTIFICATION***XXX Inc***ZAYO TTN-XXX
 Planned***
Job "run_now (trigger: date[2020-10-19 15:36:13 UTC], next run at: 2020-10-19 15:36:13 UTC)" raised an exception
Traceback (most recent call last):
  File "/opt/janitor/venv/lib64/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/janitor/app/jobs/main.py", line 169, in process
    process_provider(client, mail, p)
  File "/opt/janitor/app/jobs/main.py", line 129, in process_provider
    result = provider.process(em)
  File "/opt/janitor/app/Providers.py", line 734, in process
    result = self.add_reschedule_maint(soup, email)
  File "/opt/janitor/app/Providers.py", line 544, in add_reschedule_maint
    self.add_new_maint(soup, email)
  File "/opt/janitor/app/Providers.py", line 602, in add_new_maint
    window = line.next_sibling.strip().split('-')
TypeError: 'NoneType' object is not callable

I have no maintenances listed currently

**Comment by wasabi222** [comment]
Is this due to Zayo sending a reschedule email for a maintenance that isn't already in your db? It's also possibility that Zayo has changed their email format - they did this recently to have all times post in UTC and the template ended up breaking and I had to rewrite it. Can you post a sanitized version of the maintenance email in a gist?

**Comment by dnyt84** [comment]
Hello,

I am not good enough in Python to figure that out, tried to spend some time on it yesterday

https://gist.github.com/dnyt84/7d06b54d5321ed091a60601d69dced2f

There are 2 email chains for Maintenance Notifications.
TTN-00044xxxx1
TTN-00044xxxx5

The TTN-00044xxxx5 has 2 Dates for the maintenance, not sure if that is currently implemented.

Thank you for your help!

Daniel

**Comment by dnyt84** [comment]
Here is another one that we got from Zayo:

**1st Activity Date**
10-Nov-2020 00:01 to 10-Nov-2020 06:00 ( Eastern )
10-Nov-2020 05:00 to 10-Nov-2020 11:00 ( GMT )

**Backup Date**
11-Nov-2020 00:01 to 11-Nov-2020 06:00 ( Eastern )
11-Nov-2020 05:00 to 11-Nov-2020 11:00 ( GMT )

**Comment by dnyt84** [comment]
Good Morning, 

Does not appear that they have any standard on time zones ... this MR came in today from Zayo:

**Maintenance Window**

**1st Activity Date**
30-Nov-2020 23:00 to 01-Dec-2020 05:00 ( GMT )

**Backup Date**
01-Dec-2020 23:00 to 02-Dec-2020 05:00 ( GMT )

**Location of Maintenance:** France
