### ISSUE TITLE
Error while processing maintenance

### ISSUE THREAD

**Issue by mirceaulinic** [wasabi222/janitor#7]
```python
Job "run_loop (trigger: interval[0:05:00], next run at: 2019-07-29 13:44:52 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/janitor/app/__init__.py", line 25, in process_startup
    process()
  File "/opt/janitor/app/jobs/main.py", line 83, in process
    process_provider(client, mail, p)
  File "/opt/janitor/app/jobs/main.py", line 43, in process_provider
    result = provider.process(em)
  File "/opt/janitor/app/Providers.py", line 767, in process
    result = self.add_new_maint(soup, email)
  File "/opt/janitor/app/Providers.py", line 630, in add_new_maint
    start_re = re.search(r'Start: (.*)\r', soup.text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by wasabi222** [comment]
I believe this one is fixed with the `all()` and raising a parsing error - feel free to re-open if it's not.
